### ISSUE TITLE
Failed to compile on Windows 10 64-bit

### ISSUE THREAD

**Issue by bmomartins** [manugarg/pacparser#114]
Hello team,

I was about to start testing this product, but it looks like I am having a compilation error:

`C:\pacparser-1.3.7>make -C src -f Makefile.win32 pymod
make: Entering directory 'C:/pacparser-1.3.7/src'
make -C spidermonkey -f Makefile.win32
make[1]: Entering directory 'C:/pacparser-1.3.7/src/spidermonkey'
gcc.exe -D_IEEE_LIBM -DEXPORT_JS_API -DWIN32 -D_MINGW -D_WINDOWS -DXP_WIN -s   -c -o js/src/jsnum.o js/src/jsnum.c
js/src/jsnum.c: In function 'js_InitRuntimeNumberState':
js/src/jsnum.c:531:30: error: 'MCW_EM' undeclared (first use in this function)
 #define FIX_FPU() _control87(MCW_EM | PC_53, MCW_EM | MCW_PC)
                              ^
js/src/jsnum.c:549:5: note: in expansion of macro 'FIX_FPU'
     FIX_FPU();
     ^~~~~~~
js/src/jsnum.c:531:30: note: each undeclared identifier is reported only once for each function it appears in
 #define FIX_FPU() _control87(MCW_EM | PC_53, MCW_EM | MCW_PC)
                              ^
js/src/jsnum.c:549:5: note: in expansion of macro 'FIX_FPU'
     FIX_FPU();
     ^~~~~~~
js/src/jsnum.c:531:39: error: 'PC_53' undeclared (first use in this function)
 #define FIX_FPU() _control87(MCW_EM | PC_53, MCW_EM | MCW_PC)
                                       ^
js/src/jsnum.c:549:5: note: in expansion of macro 'FIX_FPU'
     FIX_FPU();
     ^~~~~~~
js/src/jsnum.c:531:55: error: 'MCW_PC' undeclared (first use in this function)
 #define FIX_FPU() _control87(MCW_EM | PC_53, MCW_EM | MCW_PC)
                                                       ^
js/src/jsnum.c:549:5: note: in expansion of macro 'FIX_FPU'
     FIX_FPU();
     ^~~~~~~
js/src/jsnum.c: In function 'js_InitNumberClass':
js/src/jsnum.c:531:30: error: 'MCW_EM' undeclared (first use in this function)
 #define FIX_FPU() _control87(MCW_EM | PC_53, MCW_EM | MCW_PC)
                              ^
js/src/jsnum.c:613:5: note: in expansion of macro 'FIX_FPU'
     FIX_FPU();
     ^~~~~~~
js/src/jsnum.c:531:39: error: 'PC_53' undeclared (first use in this function)
 #define FIX_FPU() _control87(MCW_EM | PC_53, MCW_EM | MCW_PC)
                                       ^
js/src/jsnum.c:613:5: note: in expansion of macro 'FIX_FPU'
     FIX_FPU();
     ^~~~~~~
js/src/jsnum.c:531:55: error: 'MCW_PC' undeclared (first use in this function)
 #define FIX_FPU() _control87(MCW_EM | PC_53, MCW_EM | MCW_PC)
                                                       ^
js/src/jsnum.c:613:5: note: in expansion of macro 'FIX_FPU'
     FIX_FPU();
     ^~~~~~~
<builtin>: recipe for target 'js/src/jsnum.o' failed
make[1]: *** [js/src/jsnum.o] Error 1
make[1]: Leaving directory 'C:/pacparser-1.3.7/src/spidermonkey'
Makefile.win32:37: recipe for target 'js.lib' failed
make: *** [js.lib] Error 2
make: Leaving directory 'C:/pacparser-1.3.7/src'
`

Can someone please guide me?

Thank you!

**Comment by rushikeshkorde** [comment]
@bmomartins Try this https://github.com/manugarg/pacparser/issues/98

**Comment by manugarg** [comment]
For me compilation worked without any changes. I used 64-bit mingw64 though, not sure if that matters. I'll upload a prebuilt release soon.

**Comment by manugarg** [comment]
I've uploaded the latest builds. Also, updated a bunch of build scripts.
