### ISSUE TITLE
Python 3.11 Compatibility

### ISSUE THREAD

**Issue by cliftonHPE** [manugarg/pacparser#143]
Is Python 3.11 support on the immediate roadmap? Pacparser is used in some of our repositories which we are upgrading to python 3.11, however the below error gets thrown. 

`pip._internal.exceptions.DistributionNotFound: No matching distribution found for pacparser==1.4.0`

**Comment by manugarg** [comment]
Yes, it's been added actually, though I haven't released it after that yet. You can install it by specifying the dev version for now:
pacparser==1.4.0.dev3

I'll cut a new release soon.

**Comment by manugarg** [comment]
It's done. 1.4.1 has binaries for Python3.11:
https://pypi.org/project/pacparser/1.4.1/#files
