### ISSUE TITLE
issue for read_file_into_str in pacparser.c

### ISSUE THREAD

**Issue by ripplehang** [manugarg/pacparser#167]
`static char*                      // File content in string or NULL if failed.
read_file_into_str(const char* filename)
{
	FILE* fptr = fopen(filename, "r");
	if (fptr == NULL) return NULL;

	if (fseek(fptr, 0L, SEEK_END) != 0) goto error2;
	long file_size = ftell(fptr);
	if (file_size == -1) goto error2;
	if (fseek(fptr, 0L, SEEK_SET) != 0) goto error2;

	char* str = (char*)malloc(file_size + 1);
	if (str == NULL) goto error2;

	// Read the file into the string
	size_t bytes_read = fread(str, 1, file_size, fptr);
	if (bytes_read != file_size) {
		free(str);
		goto error2;
	}

	// This check should not be needed but adding this satisfies
	// sonarlint static analysis, otherwise it complains about tainted
	// index.
	if (bytes_read < file_size + 1) {
		str[bytes_read] = '\0';
	}
	fclose(fptr);
	return str;
error2:
	fclose(fptr);
	return NULL;
}`
there is a issue in the above piece of code,  when the pac file is created on windows, the line is usually ends with '\r\n' ,

 if fopen with only 'r'(without 'b'), the file_size would treat the '\r\n' as two bytes,that means, if a pac file only contains '\r\n', then the file_size would be 2, however, the fread would only return 1, then the condition if (bytes_read != file_size) would always be true for the windows pac file.
the fix solution is to add the 'b' for fopen, function.  fopen(filename, "r");->  fopen(filename, "rb");
I've tested locally, it should work.
@manugarg can you review the bug,
Thanks

**Comment by manugarg** [comment]
Apologies for missing this so far. This function works fine (fopen with 'r' should do the right thing) on Windows or Unix -- CI tests run on the both the systems. I wonder if you were reading a Windows file on Linux or something like that? I believe (not sure) that on Linux, fopen with 'r', will not convert '\r\n' to '\n'. Reading file in binary mode with 'rb' may be okay, but I'll experiment a bit more to be sure.

**Comment by ripplehang** [comment]
@manugarg Thanks for your reply. 
The issue could be stable reproduced in windows(just create the pac file with windows ending \r\n and reading the file on windows), as described in my original description, if fopen with only 'r'(without 'b'),  the fread would only return 1 rather than 2 in this case, then the filesize(2) mismatches.
can you help to test the simple code on windows? or can you point out  which unit/component test that already cover case, so that i would take a took at the  test case?
Thanks

**Comment by manugarg** [comment]
You're right. I understand the issue now. fread will not read "\r" on Windows if file lines end in "\r\n". Hence bytes read and file size will never match. We can try using "rb". Sending a PR.

**Comment by manugarg** [comment]
PR is submitted. It will go out in the next release.
