### ISSUE TITLE
updated support for latest spidermonkey ( 1.8.5 actually)

### ISSUE THREAD

**Issue by manugarg** [manugarg/pacparser#33]
_From [bo...@steki.net](https://code.google.com/u/106661645171067716109/) on March 14, 2014 03:23:12_

attached patches help un-bundling and using latest (1.8.5) spidermonkey

_Original issue: http://code.google.com/p/pacparser/issues/detail?id=33_

**Comment by cwittmer** [comment]
And when are you going to use these ?

**Comment by davidlt** [comment]
We should move to at least 1.8.5 + patch to support 48-bit VA on AArch64. See: #86

**Comment by manugarg** [comment]
This issue is too old now, and we are in no position of investing in the new spidermonkey build :(. Sorry.
