### ISSUE TITLE
FindProxyForURLEx does not work in 1.3.5

### ISSUE THREAD

**Issue by DrDaveD** [manugarg/pacparser#55]
The release announcement for 1.3.5 says FindProxyForURLEx is supported, but it does not work if you define that instead of FindProxyForURL.  It returns an error 
`pacparser.c: pacparser_find_proxy: Javascript function FindProxyForURL not defined.`
I see FindProxyForURLEx getting called from a function findProxyForURL in pac_utils.h, but findProxyForURL is not referenced anywhere, and pacparser_find_proxy still requires FindProxyForURL.  If I change all occurrences of FindProxyForURL to findProxyForURL in pacparser.c, it works.

**Comment by DrDaveD** [comment]
Made pull request #56 for this

**Comment by manugarg** [comment]
This pull request has been merged. Leaving this issue open until next release.
