### ISSUE TITLE
lack of init function (PyInit_pacparser)

### ISSUE THREAD

**Issue by Sanyorke-Han** [manugarg/pacparser#59]
Hi,
     I download the 1.3.5 release binary package, and install well on windows 7 with python 3.4. I added system search path to MinGW (that pacparser.dll required), when import pacparser, it report error:
ImportError: dynamic module does not define init function (PyInit_pacparser)

hope I can get a fix version soon.
thanks.

**Comment by manugarg** [comment]
How did you install the package? I just checked and found that the Windows install script is broken. From your error message it seems that you have installed pacparser for python 2.7 version.

To reinstall the correct version:

1. Delete "pacparser" folder from your python installation's site-packages, usually found at "C:\Python34\Lib\site-packages", but depends on your installation.
2. Download the pacparser package from here: https://github.com/pacparser/pacparser/releases/download/1.3.5/pacparser-python34-1.3.5-win32.zip
3. Unzip it, and copy the "pacparser" folder inside it to the site-packages folder mentioned in step 1.
