### ISSUE TITLE
./pactest: error while loading shared libraries: libpacparser.so.1

### ISSUE THREAD

**Issue by indy2005** [manugarg/pacparser#60]
I have compiled on RHEL 6.7 and am receiving this error when trying to run pacparser.

./pactest: error while loading shared libraries: libpacparser.so.1: cannot open shared object file: No such file or directory.  I do see the file in /usr/lib.

**Comment by DrDaveD** [comment]
Do you have an LD_LIBRARY_PATH set that does not include /usr/lib?

**Comment by manugarg** [comment]
Closing this as it seems like a system configuration issue.
