### ISSUE TITLE
Precompiled pactester doesn't work in Windows

### ISSUE THREAD

**Issue by nice-try-bro** [manugarg/pacparser#74]
Windows 10 x64 Pro.
I am using precompiled binary from pacparser-1.3.3-win32.zip.
First run:

> The program can't start because libgcc_s_dw2-1.dll is missing from your computer. Try reinstalling the program to fix this problem. 

I put random libgcc_s_dw2-1.dll found on my PC in diffferrent app folder and get following:

> The application was unable to start correctly (0xc000007b). Click OK to close the application.

**Comment by Guttz** [comment]
The tool work just fine for on me Windows 7 x64. Downloaded the dll in the first link on google.

 Note that it is a command line tool and must be used from the cmd.
