### ISSUE TITLE
Fails to build on x86 and armhf due to undefined reference to __va_copy

### ISSUE THREAD

**Issue by jirutka** [manugarg/pacparser#77]
```
make -j1 -C src pactester pymod
...
cd js/src
find . -name "libjs.a" -exec cp -f {} .. \;
make[1]: Leaving directory '/home/buildozer/aports/testing/pacparser/src/pacparser-1.3.6/src/spidermonkey'
gcc -shared -g -DXP_UNIX -Wall -DVERSION=v3.4.0-247-g939ac0d -Ispidermonkey/js/src -Wl,--as-needed -Wl,-soname=libpacparser.so.1 -Wl,-exclude-libs=libjs.a -o libpacparser.so.1 pacparser.o libjs.a -lm
ln -sf libpacparser.so.1 libpacparser.so
gcc -g -DXP_UNIX -Wall -DVERSION=v3.4.0-247-g939ac0d -Ispidermonkey/js/src -Wl,--as-needed pactester.c -o pactester -lpacparser -L. -I.
./libpacparser.so: undefined reference to `__va_copy'
collect2: error: ld returned 1 exit status
make: *** [Makefile:99: pactester] Error 1
make: Leaving directory '/home/buildozer/aports/testing/pacparser/src/pacparser-1.3.6/src'
```

It builds fine only on x86_64.

**Comment by manugarg** [comment]
Digging this a bit further, I changed Makefile to set HAVE_VA_COPY in Sep 2010, by this change:
https://github.com/pacparser/pacparser/commit/53ebc463364773a4ef4ff026f7f12a62de28b752#diff-f57f2991a6aa25fe45d8036c51bf8b4d

Not sure why it wasn't reported until now. Also, debian is able to build it just fine:
https://packages.debian.org/unstable/libpacparser1

**Comment by manugarg** [comment]
On further investigation, it seems that GCC defines MACRO __va_copy to be a builtin:
https://github.com/gcc-mirror/gcc/blob/master/gcc/ginclude/stdarg.h#L54

I wonder why are you getting this error. I'll try to build it myself to see if I can reproduce it.

**Comment by guangzhi-ran** [comment]
See this issue on apline. Works by replacing __va_copy with va_copy.

**Comment by manugarg** [comment]
This issue is super old now. Please re-open if it's still an issue.

**Comment by ptrcnull** [comment]
it is still an issue: https://gitlab.alpinelinux.org/ptrcnull/aports/-/jobs/931243
```
gcc -g -DXP_UNIX -Wall -DVERSION= -Ispidermonkey/js/src -Wl,--as-needed,-O1,--sort-common pactester.c pacparser.o spidermonkey/libjs.a -o pactester -lm -L. -I.
/usr/lib/gcc/i586-alpine-linux-musl/12.2.1/../../../../i586-alpine-linux-musl/bin/ld: spidermonkey/libjs.a(jsprf.o): in function `BuildArgArray':
/builds/ptrcnull/aports/testing/pacparser/src/pacparser-1.4.0/src/spidermonkey/js/src/jsprf.c:644: undefined reference to `__va_copy'
```

please reopen the issue

**Comment by ptrcnull** [comment]
why is `__va_copy` even used instead of just `va_copy` (which is [standardized][1] and widely used)?

it looks like 53ebc463364773a4ef4ff026f7f12a62de28b752 was some weird debian ppc workaround, is there any issue / bug report related to that?

[1]: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdarg.h.html

**Comment by nekopsykose** [comment]
> why is __va_copy even used instead of just va_copy (which is [standardized](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdarg.h.html) and widely used)?  

because this code is much older than you think, and the 'standardised' va_copy wasn't really standardised prior to 2011/10. i forget which standard.

so, at the time, on powerpc32 (yes, that old), va_copy most likely didn't exist, but the libc provided __va_copy to not clash with a potential future implementation. you'll have to do some archaelogical digging to find it for sure.

these days though, sure, as long as you target the new standards you can use `va_copy` instead.

**Comment by ptrcnull** [comment]
> the 'standardised' va_copy wasn't really standardised prior to 2011/10

from what i've been able to find (it's a bit unclear though, as the [standard costs 60 dollars to download (😠)][1]), `va_copy` was supposed to be guaranteed to exist since at least C99

[1]: https://webstore.ansi.org/standards/incits/incitsisoiec98991999r2005

**Comment by moszajca** [comment]
Still an issue on Alpine:
```
6.215 python ../tests/runtests.py
6.229 Build dir: %s /app/pacparser-1.4.2/src/../tests/../src/pymod/build
6.229 ['lib.linux-aarch64-cpython-311', 'temp.linux-aarch64-cpython-311']
6.229 Traceback (most recent call last):
6.229   File "/app/pacparser-1.4.2/src/../tests/runtests.py", line 47, in runtests
6.229     import pacparser
6.229   File "/app/pacparser-1.4.2/src/../tests/../src/pymod/build/lib.linux-aarch64-cpython-311/pacparser/__init__.py", line 31, in <module>
6.230     from pacparser import _pacparser
6.230 ImportError: Error relocating /app/pacparser-1.4.2/src/../tests/../src/pymod/build/lib.linux-aarch64-cpython-311/pacparser/_pacparser.cpython-311-aarch64-linux-musl.so: __va_copy: symbol not found
```

Using `va_copy` fixes it

**Comment by manugarg** [comment]
I think I understand this issue better now. Alpine uses musl for C library and musl doesn't define __va_copy. I'll submit a fix soon.

**Comment by manugarg** [comment]
It guess it's more than just alpine being an issue. It's the combination of alpine and some platforms. In any case, it seems better choice is to use va_copy everywhere now. I've done that.

**Comment by moszajca** [comment]
@manugarg thanks for the update. Do you plan to release it soon?

**Comment by manugarg** [comment]
Yeah, I plan to cut a release in a couple of days.
