### ISSUE TITLE
1.3.5 test fails with incorrect error code

### ISSUE THREAD

**Issue by nieder** [manugarg/pacparser#79]
On OS X 10.11, v1.3.5 (and v1.3.1) fails selftests with this error:

```
Running tests for pactester.
NO_INTERNET= ../tests/runtests.sh
Test failed: got "END-OF-SCRIPT", expected "isNotResolvable"
Command tried: /sw/build.build/pacparser-1.3.5-1/pacparser-1.3.5/tests/../src/pactester -p /sw/build.build/pacparser-1.3.5-1/pacparser-1.3.5/tests/proxy.pac -u http://www.notresolvabledomainXXX.com
Running with debug mode on...
DEBUG=1 /sw/build.build/pacparser-1.3.5-1/pacparser-1.3.5/tests/../src/pactester -p /sw/build.build/pacparser-1.3.5-1/pacparser-1.3.5/tests/proxy.pac -u http://www.notresolvabledomainXXX.com
END-OF-SCRIPT
make: *** [testpactester] Error 1
```

If I replace isNotResolvable with END-OF-SCRIPT in tests/testdata then the test passes, but I don't know if END-OF-SCRIPT is an expected error message or if it is a sign of a deeper problem in the pacparser program.

**Comment by manugarg** [comment]
I am not able to reproduce this. This seems something specific to your local environment setup. I wonder if your system is set to resolve all hostnames to some standard IP (some sort of internet accelerator layer for example.

Can you tell me what do you get when you run:
host www.notresolvabledomainXXX.com

**Comment by nieder** [comment]
~~~~
nieder $ host www.notresolvabledomainXXX.com
www.notresolvabledomainXXX.com has address 198.105.244.114
www.notresolvabledomainXXX.com has address 198.105.254.114
Host www.notresolvabledomainXXX.com not found: 3(NXDOMAIN)
~~~~

As far as I know, there's nothing in my system (software or environment) that should affect network resolving. It's a stock OS X system. I do have Frontier as my ISP, which sometimes resolves DNS when it shouldn't, as it looks like it's doing now :(

**Comment by richandersn** [comment]
I am a Frontier FiOS user as well and had the same problem.  Frontier's DNS servers resolve www.notresolvabledomainXXX.com to their search portal rather than returning an error (which is really obnoxious behavior on the part of Frontier).  I set DNS servers to point to OpenDNS and pacparser compiled and installed as expected.

**Comment by nieder** [comment]
This then seems to be a Frontier issue (or any ISP that resolves unresolveable domains. Now the tests are passing for me and http://www.notresolvabledomainxxx.com/ comes back as a server not found error in the browser.
