### ISSUE TITLE
Release a new version of pacparser

### ISSUE THREAD

**Issue by manugarg** [manugarg/pacparser#85]
It's been more than a year since last release and there are quite a few fixes (e.g. #81, #71), that need to go in.

**Comment by grahampugh** [comment]
Also, the latest DMG doesn't work on macOS Sierra.

**Comment by manugarg** [comment]
Working on it right now.

**Comment by manugarg** [comment]
Cut a new release. Apart from the source tarball, uploaded only Mac package for now.
