### ISSUE TITLE
SpiderMonkey (1.8.5) + support 48-bit VA on AArch64

### ISSUE THREAD

**Issue by davidlt** [manugarg/pacparser#86]
In order to support some AArch64 silicons and new workflows distributions are looking to move to 48-bit VA on AArch64. That's one bit more than you get on x86_64.

CentOS 7.3: https://lists.centos.org/pipermail/arm-dev/2016-November/002413.html
Fedora 26: https://fedoraproject.org/wiki/Changes/aarch64-48bitVA

Patch for 1.8.5 is provided here: https://bugzilla.redhat.com/show_bug.cgi?id=1242326

Note, that this will change ABI for old 1.8.5 (js) if one is using new SpiderMonkey (mozjs) ABI is unaffected. That shouldn't affect pacparser as it bundles old SpiderMonkey.

**Comment by manugarg** [comment]
This issue is too old now, and we are in no position of investing in the new spidermonkey build :(. Sorry.
