### ISSUE TITLE
ImportError The specified module could not be found.

### ISSUE THREAD

**Issue by Monastario** [manugarg/pacparser#87]
Hello Guys,

I have a problem with pacparser on one of the machines. It is working with the same settings on another PC so I have no idea what to look for and how to fix it. The problem is that while trying to run the application, the error comes up in the PyCharm:

"File "C:\Python34\lib\site-packages\pacparser\__init__.py", line 31, in <module>
    from pacparser import _pacparser
ImportError: DLL load failed: The specified module could not be found."

All of the files are placed there so I have no idea why I see this error. I have 32-bit Python on 64-bit Windows 7 (Python 3.4.4 and pacparser - pacparser-python34-1.3.5-win32). As I mentioned before the same setup works on another machine so I do not really know what the difference is and how to fix it. Is anybody able to help with that one?

Best Regards,

**Comment by manugarg** [comment]
New python3 builds on pypi (instal using pip install pacparser) should always work.
