### ISSUE TITLE
Solution: ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by vinamra2004** [manugarg/pacparser#88]
I am running python 2.7 32 bit on 64 bit winserver 2008 R2 Ent. 
I copied the pacparser to site-packages and when I imported pacparser I got following error 

ImportError: DLL load failed: The specified module could not be found.

The solution is to download libgcc_s_dw2-1.dll from MinGW to Python32\Lib\site-packages\pacparser\

it will work after coping this dll.

if you dont have this dll then install MinGW on this system or any other and copy paste it here.

i hope it helps

**Comment by letlet** [comment]
This does work! Thank u so much

**Comment by corningsun** [comment]
有用，非常感谢！

**Comment by manugarg** [comment]
Latest python 3 builds uploaded on pypi don't require any DLLs. I'll recommend using them.
