### ISSUE TITLE
publishing issue

### ISSUE THREAD

**Issue by igaralf** [manugarg/pacparser#92]
Hello
I'm facing an issue when trying to publis my pac to the respective servers.
I have several locations in my pac. Whenever i try to publish, i get a message like the one below for each one of the locations:
ERROR, https://nonexistingdomain SHOULD RETURN DIRECT, but returns PROXY 192.168.7.9:8080 instead!
Location: Location1, test IP: 192.168.0.1 
That nonexistign domain does not have any entry in the pac file, nor is it resolvable.

**Comment by manugarg** [comment]
@igaralf can you please verify that it's not same as https://github.com/manugarg/pacparser/issues/79 (are using frontier ISP by any chance?)

**Comment by manugarg** [comment]
@igaralf Closing it due to lack of more information. Feel free to reopen.
