### ISSUE TITLE
Solution : Compiling Pacparser for python 3.7 on win 10

### ISSUE THREAD

**Issue by Atply234** [manugarg/pacparser#98]
For anyone facing issue with compiling pacpaser for **Python 3.7** on **Win 10**, Please follow the below:

1) Edit the float.h file under MinGW directory and remove the underscore from the below definitions:
- **MCW_EM**
- **MCW_PC**
- **PC_53**

2) Add the below to the pacparser.c file:
**#define _WIN32_WINNT 0x0501**

3) Also download spidermonkey from the below URL and extract the contents to /src/spidermonkey , as the fdlibm directory is not included in the pacparser zip file:
          [https://ftp.mozilla.org/pub/spidermonkey/releases/1.7.0/](url)

4) Then run below command:
        **make -C src -f Makefile.win32 dist**

5) For some reason the below did not work for me, therefore i manually copied over the python37.dll to the /src/pymod directory and commented the below lines in the Makefile.win32
          **#python$(PY_VER).dll:**
          **#copy $(PY_DLL) python$(PY_VER).dll**

6) Run the below command, and a pacpaser-python37 directory will be created:
**make -C src -f Makefile.win32 pymod**
7) Use the install.py to copy the files to site-packages,
8) Done

Hope this helps.
Let me know if anyone faces any other issues, ill be happy to help.

**Comment by rushikeshkorde** [comment]
@Atply234 I am facing this issue
https://github.com/manugarg/pacparser/issues/115

**Comment by manugarg** [comment]
Recent changes should make it work for all, given you install the mingw64 tools using the msys2 installer from here: https://www.msys2.org/.

**Comment by manugarg** [comment]
See https://github.com/manugarg/pacparser/commit/6c615e220ee692b61564dd008841f7e9813e56c0 for how you don't need to compile python module anymore, for most of the cases.
